global:
  scrape_interval: 10s
  external_labels:
    origin_prometheus: prometheus01

scrape_configs:
  - job_name: 'spring_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.15.7:8080']

remote_write:
  - url: https://prometheus-us-central1.grafana.net/api/prom/push
    basic_auth:
      username: 43438
      password: <add token here>
        #docker run -d -p 9090:9090 -v C:\Users\X270\OneDrive\Java\springboot-monitoring-prometheus-grafana\prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus
