global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spring_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.15.7:8080']

        #docker run -d -p 9090:9090 -v C:\Users\X270\OneDrive\Java\springboot-monitoring-prometheus-grafana\prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus
